default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Behat\MinkExtension\Context\MinkContext
        - PaulGibbs\WordpressBehatExtension\Context\ContentContext
        - PaulGibbs\WordpressBehatExtension\Context\DashboardContext
        - PaulGibbs\WordpressBehatExtension\Context\SiteContext
        - PaulGibbs\WordpressBehatExtension\Context\UserContext
        - PaulGibbs\WordpressBehatExtension\Context\WordpressContext
        - PaulGibbs\WordpressBehatExtension\Context\EditPostContext
        - PaulGibbs\WordpressBehatExtension\Context\WidgetContext

  extensions:
    Behat\MinkExtension:
      base_url: http://wordhat.dev
      browser_name: chrome
      default_session: default
      javascript_session: selenium2
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false  # Allow self-signed SSL certificates
        selenium2:
          selenium2:
            wd_host: 'http://selenium:4444/wd/hub'

    PaulGibbs\WordpressBehatExtension:
      path: /var/www/html
      users:
        admin:
          username: admin
          password: admin
      wpcli:
        binary: wp --allow-root

    Bex\Behat\ScreenshotExtension:
      active_image_drivers: upload_pie
      image_drivers:
        upload_pie:
          expire: '30m'
